# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use Node.js image
FROM node:18-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY src/dify/package.json /app/package.json

# Install dependencies without running scripts
RUN npm install --ignore-scripts

# Copy the rest of the application source code
COPY src/dify /app

# Build the application
RUN npm run build

# Use a minimal Node.js runtime image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy built files from the builder stage
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package.json /app/package.json

# Set environment variables (if needed)
# ENV DIFY_API_KEY=<your-api-key>
# ENV DIFY_API_ENDPOINT=<your-api-endpoint>

# Set the command to run the application
ENTRYPOINT ["node", "dist/index.js"]
